INSERT INTO educationLevels (id, value) values (1, 'LICENZA ELEMENTARE');
INSERT INTO educationLevels (id, value) values (2, 'LICENZA MEDIA');
INSERT INTO educationLevels (id, value) values (3, 'DIPLOMA DI ISTRUZIONE SECONDARIA SUPERIORE');
INSERT INTO educationLevels (id, value) values (4, 'LAUREA DI PRIMO LIVELLO');
INSERT INTO educationLevels (id, value) values (5, 'LAUREA SPECIALISTICA');
INSERT INTO educationLevels (id, value) values (6, 'MASTER UNIVERSITARIO DI PRIMO LIVELLO');
INSERT INTO employments (id, value) values (1, 'STUDENTE');
INSERT INTO employments (id, value) values (2, 'DISOCCUPATO');
INSERT INTO employments (id, value) values (3, 'OCCUPATO AUTONOMO');
INSERT INTO employments (id, value) values (4, 'OCCUPATO PERMANENTE');
INSERT INTO employments (id, value) values (5, 'OCCUPATO TEMPORANEO');
INSERT INTO employments (id, value) values (6, 'PENSIONATO');
INSERT INTO fuels (id, value) values (1, 'BENZINA');
INSERT INTO fuels (id, value) values (2, 'DIESEL');
INSERT INTO fuels (id, value) values (3, 'GPL');
INSERT INTO fuels (id, value) values (4, 'IBRIDA');
INSERT INTO fuels (id, value) values (5, 'METANO');
INSERT INTO fuels (id, value) values (6, 'AUTO ELETTRICA');
INSERT INTO carSharingServices (id, name) values (1, 'ENJOY');
INSERT INTO carSharingServices (id, name) values (2, 'CAR2GO');
INSERT INTO carSharingServices (id, name) values (3, 'BLUETORINO');
INSERT INTO travelDocuments (id, name) values (1, 'GIORNALIERO');
INSERT INTO travelDocuments (id, name) values (2, 'CORSA SINGOLA');
INSERT INTO travelDocuments (id, name) values (3, 'CARNET 5');
INSERT INTO travelDocuments (id, name) values (4, 'CARNET 15');
INSERT INTO status (id, value) values (1, 'INCOMPLETE');
INSERT INTO status (id, value) values (2, 'ENABLED');
INSERT INTO status (id, value) values (3, 'BANNED');
