INSERT INTO IstrTable (id_istr, nome) values (1, 'LICENZA ELEMENTARE');
INSERT INTO IstrTable (id_istr, nome) values (2, 'LICENZA MEDIA');
INSERT INTO IstrTable (id_istr, nome) values (3, 'DIPLOMA DI ISTRUZIONE SECONDARIA SUPERIORE');
INSERT INTO IstrTable (id_istr, nome) values (4, 'LAUREA DI PRIMO LIVELLO');
INSERT INTO IstrTable (id_istr, nome) values (5, 'LAUREA SPECIALISTICA');
INSERT INTO IstrTable (id_istr, nome) values (6, 'MASTER UNIVERSITARIO DI PRIMO LIVELLO');
INSERT INTO IstrTable (id_istr, nome) values (1, 'STUDENTE');
INSERT INTO IstrTable (id_istr, nome) values (2, 'DISOCCUPATO');
INSERT INTO IstrTable (id_istr, nome) values (3, 'OCCUPATO AUTONOMO');
INSERT INTO IstrTable (id_istr, nome) values (4, 'OCCUPATO PERMANENTE');
INSERT INTO IstrTable (id_istr, nome) values (5, 'OCCUPATO TEMPORANEO');
INSERT INTO IstrTable (id_istr, nome) values (6, 'PENSIONATO');
INSERT INTO CarbTable (id_carb, nome) values (1, 'BENZINA');
INSERT INTO CarbTable (id_carb, nome) values (2, 'DIESEL');
INSERT INTO CarbTable (id_carb, nome) values (3, 'GPL');
INSERT INTO CarbTable (id_carb, nome) values (4, 'GASOLIO');
INSERT INTO CarbTable (id_carb, nome) values (5, 'METANO');
INSERT INTO CarbTable (id_carb, nome) values (6, 'AUTO ELETTRICA');
INSERT INTO FornTable (id_forn, nome) values (1, 'ENJOY');
INSERT INTO FornTable (id_forn, nome) values (2, 'CAR2GO');
INSERT INTO FornTable (id_forn, nome) values (3, 'BLUETORINO');
INSERT INTO FreqTable (id_freq, nome) values (1, 'BUS');
INSERT INTO FreqTable (id_freq, nome) values (2, 'TRAM');
INSERT INTO FreqTable (id_freq, nome) values (3, 'METRO');
INSERT INTO FreqTable (id_freq, nome) values (4, 'TAXI');
INSERT INTO StatoTable (id_stato, nome) values (1, 'AUTENTICATO');
INSERT INTO StatoTable (id_stato, nome) values (2, 'NON_AUTENTICATO');
INSERT INTO StatoTable (id_stato, nome) values (3, 'BANNATO');